export const FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN = process.env.REACT_APP_FIREBASE_AUTH_DOMAIN;
export const FIREBASE_STORAGE_BUCKET = process.env.REACT_APP_FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGING_SENDER_ID = process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID;

export const API_DOMAIN = process.env.REACT_APP_API_DOMAIN;

export const LIVEKIT_URL = process.env.REACT_APP_LIVEKIT_URL;

export const SET_AUTH = process.env.REACT_APP_SET_AUTH;

export const DISABLE_TWILIO_CONVERSATIONS = process.env.REACT_APP_DISABLE_TWILIO_CONVERSATIONS;

export const TOKEN_ENDPOINT = process.env.REACT_APP_TOKEN_ENDPOINT;

export const ROOM_TYPE = process.env.REACT_APP_ROOM_TYPE;

export const GIT_TAG = process.env.REACT_APP_GIT_TAG;
export const GIT_COMMIT = process.env.REACT_APP_GIT_COMMIT;
