version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/webmoti-react"
      - "/standalone-join"
      - "/hand/app/client"
    schedule:
      interval: "weekly"
    groups:
      patch-and-minor-updates:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/hand/app"
    schedule:
      interval: "weekly"
    groups:
      patch-and-minor-updates:
        update-types:
          - "patch"
          - "minor"
