version: "3.8"

services:
  fastapi-app:
    image: arm64v8/debian:bookworm
    container_name: server-container
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /home/imdc1/app:/app
    working_dir: /app
    command: bash
