version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.5.3
  python: circleci/python@3.1.0

parameters:
  build-and-test-react-app:
    type: boolean
    default: false
  test-hand-server:
    type: boolean
    default: false

jobs:
  build-and-test-react-app:
    docker:
      - image: cimg/node:22.16.0-browsers

    steps:
      - run:
          name: Halt if no files changed
          command: |
            if [ "<< pipeline.parameters.build-and-test-react-app >>" != "true" ]; then
              echo "Skipping build-and-test-react-app — no matching files changed."
              circleci-agent step halt
            fi

      - checkout

      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "webmoti-react/package-lock.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run:
          name: "Install Dependencies"
          command: |
            cd webmoti-react
            npm ci

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "webmoti-react/package-lock.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache

      - run:
          name: "Jest Unit Tests"
          command: |
            cd webmoti-react
            npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "test-reports/jest"
            JEST_JUNIT_OUTPUT_NAME: "results.xml"
            JEST_JUNIT_CLASSNAME: "{classname}"
            JEST_JUNIT_TITLE: "{title}"

      - store_artifacts:
          path: webmoti-react/coverage

      - run:
          name: "Eslint"
          command: |
            cd webmoti-react
            npm run lint -- --max-warnings 0

      - run:
          name: "Check server types"
          command: |
            cd webmoti-react
            npm run typescript:server

      - run:
          name: "Set environment variables for local token server (used by Cypress tests)"
          command: |
            cd webmoti-react
            echo TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID >> .env
            echo TWILIO_API_KEY_SID=$TWILIO_API_KEY >> .env
            echo TWILIO_API_KEY_SECRET=$TWILIO_API_SECRET >> .env
            echo TWILIO_CONVERSATIONS_SERVICE_SID=$TWILIO_CONVERSATIONS_SERVICE_SID >> .env

      - run:
          name: "Cypress tests"
          command: |
            cd webmoti-react
            npm run cypress:ci

      - store_artifacts:
          path: webmoti-react/cypress/screenshots

      - store_test_results:
          path: webmoti-react/test-reports

  test-hand-server:
    docker:
      - image: cimg/python:3.12.4

    steps:
      - run:
          name: Halt if no files changed
          command: |
            if [ "<< pipeline.parameters.test-hand-server >>" != "true" ]; then
              echo "Skipping test-hand-server — no matching files changed."
              circleci-agent step halt
            fi

      - checkout

      - python/install-packages:
          app-dir: hand/app
          pkg-manager: pip

      - run:
          name: Run tests
          command: |
            cd hand/app
            pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')

      - store_test_results:
          path: hand/app/junit.xml

workflows:
  react-app:
    jobs:
      - build-and-test-react-app:
          filters:
            tags:
              only: /.*/

  hand-server:
    jobs:
      - test-hand-server:
          filters:
            tags:
              only: /.*/
