services:
  webmoti-server-app:
    image: arm64v8/debian:bookworm
    container_name: webmoti-server-container
    privileged: true
    platform: linux/arm64
    ports:
      - "8080:8080"
    volumes:
      - /home/imdc1/app:/app
    working_dir: /app
    command: bash
